param(
  [string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = 'Stop'
$outputPath = Join-Path $ProjectRoot 'catalog_generated_test.mbt'
$keySource = Get-Content -Raw (Join-Path $ProjectRoot 'contextual_detector.mbt')
$prefixSource = Get-Content -Raw (Join-Path $ProjectRoot 'prefix_detector.mbt')
$builder = [System.Text.StringBuilder]::new()

[void]$builder.AppendLine('// Generated by tools/generate_catalog_tests.ps1. Do not edit by hand.')
[void]$builder.AppendLine('// Every built-in catalog entry receives an executable behavior check.')
[void]$builder.AppendLine('')

$keyPattern = 'KeyPattern::new\(\s*"([^"]+)",\s*"([^"]+)"'
$keyMatches = [regex]::Matches($keySource, $keyPattern)
$index = 0
foreach ($match in $keyMatches) {
  $detector = $match.Groups[1].Value
  $key = $match.Groups[2].Value
  $safeName = ($detector + '-' + $key) -replace '[^A-Za-z0-9_-]', '-'
  $value = 'A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6'
  [void]$builder.AppendLine('///|')
  [void]$builder.AppendLine(('test "catalog key {0:D3} {1}" {{' -f $index, $safeName))
  [void]$builder.AppendLine(('  let result = @lunasieve.scan("{0}=" + "{1}")' -f $key, $value))
  [void]$builder.AppendLine(('  assert_true(result.findings.any(fn(finding) {{ finding.detector_id == "{0}" }}))' -f $detector))
  [void]$builder.AppendLine('}')
  [void]$builder.AppendLine('')
  $index += 1
}

$prefixPattern = 'PrefixPattern::new\(\s*"([^"]+)",\s*"([^"]+)",\s*(\d+)'
$prefixMatches = [regex]::Matches($prefixSource, $prefixPattern)
$index = 0
foreach ($match in $prefixMatches) {
  $detector = $match.Groups[1].Value
  $prefix = $match.Groups[2].Value
  $minimum = [int]$match.Groups[3].Value
  $tailLength = $minimum + 4
  $seed = 'A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8S9t0U1v2W3x4Y5z6'
  while ($seed.Length -lt $tailLength) {
    $seed += 'A1b2C3d4'
  }
  $tail = $seed.Substring(0, $tailLength)
  $safeName = $detector -replace '[^A-Za-z0-9_-]', '-'
  [void]$builder.AppendLine('///|')
  [void]$builder.AppendLine(('test "catalog prefix {0:D3} {1}" {{' -f $index, $safeName))
  [void]$builder.AppendLine(('  let result = @lunasieve.scan("{0}" + "{1}")' -f $prefix, $tail))
  [void]$builder.AppendLine(('  assert_true(result.findings.any(fn(finding) {{ finding.detector_id == "{0}" }}))' -f $detector))
  [void]$builder.AppendLine('}')
  [void]$builder.AppendLine('')
  $index += 1
}

[System.IO.File]::WriteAllText($outputPath, $builder.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Output "Generated $($keyMatches.Count) key tests and $($prefixMatches.Count) prefix tests at $outputPath"
